---
kind: pipeline
type: docker
name: default

steps:
  - name: ui-dependencies
    image: node:13-alpine
    commands:
      - npm install --prefix website
  - name: lint-ui
    image: node:13-alpine
#    depends_on:
#      - ui-dependencies
    commands:
      - npm run lint --prefix website
  - name: build-ui
    image: node:13-alpine
#    depends_on:
#      - lint-ui
    commands:
      - npm run build:prod --prefix website
  - name: test-go
    image: golang:1.13-stretch
    volumes:
      - name: docker_sock
        path: /var/run/docker.sock
    commands:
      - go test ./...
      - go test -race ./...
  - name: lint-go
    image: golang:1.13-stretch
    commands:
      - sh ./refresh-dev-env.sh
      - ./bin/golangci-lint --version
      - sh ./linter.sh
  - name: generate-go
    image: golang:1.13-stretch
#    depends_on:
#      - build-ui
#      - lint-go
    commands:
      - go get github.com/markbates/pkger/cmd/pkger
      - pkger -o cmd
  - name: build
    image: golang:1.13-stretch
#    depends_on:
#      - test-go
#      - generate-go
    commands:
      - env GOOS=linux GOARCH=amd64 go build -o ./dist/dionysos-server.linux-amd64 ./cmd/main.go
      - env GOOS=linux GOARCH=arm64 go build -o ./dist/dionysos-server.linux-arm64 ./cmd/main.go
      - env GOOS=linux GOARCH=arm go build -o ./dist/dionysos-server.linux-arm ./cmd/main.go
      - env GOOS=windows GOARCH=amd64 go build -o ./dist/dionysos-server.windows-amd64 ./cmd/main.go