---
kind: pipeline
type: docker
name: default

steps:
  - name: Download dependendies - Web UI
    image: node:13-alpine
    commands:
      - npm install --prefix website
  - name: Linting - WebUI
    image: node:13-alpine
    commands:
      - npm run lint --prefix website
  - name: Linting - Go code
    image: golang:1.13-stretch
    commands:
      - sh ./refresh-dev-env.sh
      - ./bin/golangci-lint --version
      - sh ./linter.sh
  - name: Generate - Web UI
    image: node:13-alpine
    commands:
      - npm run build:prod --prefix website
  - name: Generate - Go
    image: golang:1.13-stretch
    commands:
      - go get github.com/markbates/pkger/cmd/pkger
      - pkger -o cmd
  - name: Test
    image: golang:1.13-stretch
    commands:
      - go test ./...
      - go test -race ./...
  - name: Build
    image: golang:1.13-stretch
    commands:
      - env GOOS=linux GOARCH=amd64 go build -o ./dist/dionysos-server.linux-amd64 ./cmd/main.go
      - env GOOS=linux GOARCH=arm64 go build -o ./dist/dionysos-server.linux-arm64 ./cmd/main.go
      - env GOOS=linux GOARCH=arm go build -o ./dist/dionysos-server.linux-arm ./cmd/main.go
      - env GOOS=windows GOARCH=amd64 go build -o ./dist/dionysos-server.windows-amd64 ./cmd/main.go