parser: "vue-eslint-parser"
parserOptions:
  ecmaVersion: 11
  sourceType: module
  parser: '@typescript-eslint/parser'
env:
  browser: true
  es2020: true
extends:
  - 'plugin:vue/recommended'
  - 'plugin:@typescript-eslint/eslint-recommended'
  - 'plugin:@typescript-eslint/recommended'
  - standard
plugins:
  - vue
  - '@typescript-eslint'
rules: {}
