openapi: 3.0.0
info:
  title: Dionysos
  description: Dionysos is a software designed to manage household stock of foods and other supply.
  version: 0.0.1
servers:
  - url: http://localhost:8080/api
    description: Current server
paths:
  /items:
    get:
      summary: Returns a list of defined items.
      responses:
        '200':    # status code
          description: A JSON object containing items and query infos
          content:
            application/json:
              schema:
                type: object
                properties:
                  items:
                    type: array
                    items:
                      $ref: '#/components/schemas/Item'
        '500':
          $ref: '#/components/responses/GenericError'
components:
  schemas:
    Item:
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
      required:
        - id
        - name
    Error:
      properties:
        code:
          type: integer
        status:
          type: integer
        error:
          type: string
        time:
          type: string
          format: 'date-time'
  responses:
    GenericError:
      description: Server error happened during processing. Check error message for more details.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'